name: Node

on: [push]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node: [ '10', '6' ]

    name: ${{ matrix.node }} (Windows)
    steps:
    - name: Configure git line-breaks
      run: git config --global core.autocrlf false
    - name: Checkout Commit
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Check npm version
      # This is only necessary until we dump Node 6
      run: if [ ${{ matrix.node }} -lt 8 ]; then npm i npm@5 -g; fi;
      shell: bash
    - name: Install dependencies
      run: npm ci --ignore-scripts
    - name: Run tests
      run: npm test
      env:
        CI: true
